### ISSUE TITLE
ไม่ login ดูไม่ได้

### ISSUE THREAD

**Issue by MasterIceZ** [phakphum-dev/otog-frontend#142]
![image](https://github.com/phakphum-dev/otog-frontend/assets/64594596/a8483044-afba-408e-883b-a72a47d47f5a)
![image](https://github.com/phakphum-dev/otog-frontend/assets/64594596/fe43c52f-73e5-4722-9241-6bd1d573a761)

@Anon-136 แก้ด่วน

**Comment by Anon-136** [comment]
not a bug
