### ISSUE TITLE
แก้ Role user เป็น Admin แล้ว Password ใน Database หาย

### ISSUE THREAD

**Issue by Nepumi-Jr** [phakphum-dev/otog-frontend#26]
ตามนั้น
ไม่แน่ใจว่าเป็นที่ Front หรือ Back
แต่ตอนนี้ Password หายไปละ 3 คน LMAO😂😂😂😂😂😂😂😂😂😂😂😂

**Comment by Anon-136** [comment]
Morbin' password will be fixed in https://github.com/phakphum-dev/otog-backend/pull/11
