### ISSUE TITLE
Otog อัพไฟล์โดยใช้ปุ่มค้นหาแตก

### ISSUE THREAD

**Issue by Thunyatorn** [phakphum-dev/otog-frontend#30]

**Comment by peteza6765** [comment]
ขอบคูร๕รัยบ
ฟห

**Comment by peteza6765** [comment]
![image](https://user-images.githubusercontent.com/86222502/212484624-2ab3fc19-f7c3-4c7e-9922-e40b726fa9b7.png)

**Comment by Anon-136** [comment]
k

**Comment by Anon-136** [comment]
Probably bc, buttons are `type="submit"` by default. Will fixed later

**Comment by Anon-136** [comment]
Fixed
