### ISSUE TITLE
ตอน login เจอรูปโปรไฟล์แปลกประหลาด

### ISSUE THREAD

**Issue by Thunyatorn** [phakphum-dev/otog-frontend#34]
![image](https://user-images.githubusercontent.com/58735442/212486158-f07c80b2-0c18-4dfb-bf74-c2ba41d21f1d.jpeg)

**Comment by peteza6765** [comment]
![image](https://user-images.githubusercontent.com/86222502/212486209-982cfe52-8f4a-4d13-a4b5-b97b4e42b1fa.png)

**Comment by Anon-136** [comment]
Intentionally added as a placeholder
https://boringavatars.com/

Probably will be fixed after server component migration
