### ISSUE TITLE
Submit โค้ดเดียวกันกับโค้ดเก่าแต่ไม่ผ่าน

### ISSUE THREAD

**Issue by Thunyatorn** [phakphum-dev/otog-frontend#40]
submission ใหม่ : [56471](https://otog.cf/submission/56471)
submission เก่า : [26686](https://otog.cf/submission/26686)

**Comment by Nepumi-Jr** [comment]
skill issue

**Comment by peteza6765** [comment]
skill issue

**Comment by Thunyatorn** [comment]
skill issue

**Comment by Anon-136** [comment]
skill issue
