### ISSUE TITLE
light but to light

### ISSUE THREAD

**Issue by Thunyatorn** [phakphum-dev/otog-frontend#42]
![image](https://user-images.githubusercontent.com/58735442/215016220-eaf64b0d-48d3-4cb5-ac84-37972bc39cba.png)
ตอนเปิดเว็บครั้งแรกปุ่มปรับ theme ขึ้นให้ปรับเป็น light theme

**Comment by Anon-136** [comment]
cant reproduce

**Comment by Anon-136** [comment]
but fixed

**Comment by Anon-136** [comment]
confirmed by @MasterIceZ
