### ISSUE TITLE
Rename button

### ISSUE THREAD

**Issue by Thunyatorn** [phakphum-dev/otog-frontend#43]
![image](https://user-images.githubusercontent.com/58735442/216799322-2de8faa8-1f11-40d1-980c-41d1d1a26817.png)
ปุ่มเปลี่ยนชื่อหาย

**Comment by Anon-136** [comment]
<img width="306" alt="Screenshot 2566-02-06 at 01 26 25" src="https://user-images.githubusercontent.com/51981658/216837866-c2f8c4ae-bc0e-4101-b9de-0ddbd6edd215.png">
