### ISSUE TITLE
Login ไม่ได้แงๆ

### ISSUE THREAD

**Issue by NortGlG** [phakphum-dev/otog-frontend#64]

**Comment by Anon-136** [comment]
come to papa

**Comment by MasterIceZ** [comment]
skill issue

**Comment by Thunyatorn** [comment]
Otog ล่มเกิดได้จากหลายสาเหตุครับ แนะนำลองอ่านจากลิ้งค์นี้ดูครับ น่าจะตอบคำถามได้เข้าใจและเคลียร์ครับ
[ลิงก์จริง ไม่เกียนคับ](https://youtu.be/1BdmNJLaXtg)
