### ISSUE TITLE
ปุ่ม copy output ไม่สวยเลยย

### ISSUE THREAD

**Issue by peteza6765** [phakphum-dev/otog-frontend#71]
![image](https://user-images.githubusercontent.com/86222502/235164681-c6209b27-3fde-4731-b271-01852b058a48.png) wthhh broooo

**Comment by Anon-136** [comment]
@MasterIceZ แก้เร็ว

**Comment by MasterIceZ** [comment]
โอเค กูแก้เอง

**Comment by Anon-136** [comment]
fixed in 7c60727
