### ISSUE TITLE
โค้ดเดิม?

### ISSUE THREAD

**Issue by Thunyatorn** [phakphum-dev/otog-frontend#74]
กดแก้ไขโค้ดในข้อที่เคยผ่านแล้ว
![Screenshot 2023-04-28 233020](https://user-images.githubusercontent.com/58735442/235203623-d599b7df-6f74-4dc4-b32f-761f17394dec.png)
แล้วกด search (หรือ ctrl + k) เพื่อไปหน้าแก้ไขของข้ออื่น กลับแสดงผลโค้ดเดิม
![Screenshot 2023-04-28 233031](https://user-images.githubusercontent.com/58735442/235203724-cac33507-67d0-4c0e-b0a1-bd74493dc468.png)

**Comment by Anon-136** [comment]
oh shit

**Comment by Anon-136** [comment]
great work otog's tester!

**Comment by MasterIceZ** [comment]
OK but I'm OTOG's admin.

**Comment by Anon-136** [comment]
great work otog's admin!

**Comment by Anon-136** [comment]
fixed in ea46ffc
