### ISSUE TITLE
Admin ดู pdf โจทย์ที่ปิดอยู่ไม่ได้

### ISSUE THREAD

**Issue by MasterIceZ** [phakphum-dev/otog-frontend#75]
![image](https://user-images.githubusercontent.com/64594596/235340308-5bbdd24f-e101-4007-af80-ac6bba12ffbc.png)

**Comment by Anon-136** [comment]
<img width="731" alt="Screenshot 2566-04-30 at 14 11 09" src="https://user-images.githubusercontent.com/51981658/235340619-e95aeb8c-2377-4e5b-85ec-4c09622a6c63.png">

**Comment by MasterIceZ** [comment]
แอดมินแก้หน่อย @Anon-136

**Comment by Anon-136** [comment]
😭

**Comment by Anon-136** [comment]
แก้ยังวะ @MasterIceZ

**Comment by Anon-136** [comment]
should be fixed since https://github.com/phakphum-dev/otog-backend/commit/b8b42eecf0c181bfd3b9b5a9e924ee4230a20f2b

**Comment by Anon-136** [comment]
still bug

**Comment by Anon-136** [comment]
fixed in [45fb47c](https://github.com/phakphum-dev/otog-backend/commit/45fb47c4207c426e10a0c38abccad9ff49f42452)
