### ISSUE TITLE
ระบบเปลี่ยนชื่อไม่ทำงาน

### ISSUE THREAD

**Issue by MasterIceZ** [phakphum-dev/otog-frontend#77]
![image](https://user-images.githubusercontent.com/64594596/236053674-2ebb6f91-a7f9-4ad3-8793-a365d885d6b4.png)

**Comment by Anon-136** [comment]
intenionally removed to idk

**Comment by Anon-136** [comment]
might bring back after fully migrating to GoogleAuth
