### ISSUE TITLE
เพิ่ม desmos ลงใน otog

### ISSUE THREAD

**Issue by Thunyatorn** [phakphum-dev/otog-frontend#78]
https://www.desmos.com/
![image](https://user-images.githubusercontent.com/58735442/236526687-09ee82f0-385a-4b45-97d7-03a7a5616127.png)
หาที่เข้า desmos ผ่าน otog ไม่เจอ ทำไงวะ

**Comment by MasterIceZ** [comment]
เห็นด้วยเลย

**Comment by Anon-136** [comment]
เห็นด้วยเลย
