### ISSUE TITLE
เพิ่มสัญลักษณ์ว่ากำลังอัพโหลดไฟล์

### ISSUE THREAD

**Issue by Thunyatorn** [phakphum-dev/otog-frontend#80]
![image](https://user-images.githubusercontent.com/58735442/236638934-befae9be-2f04-423a-9550-2506dbd26b30.png)

**Comment by MasterIceZ** [comment]
ok

**Comment by Anon-136** [comment]
added in [c704c86](https://github.com/phakphum-dev/otog-frontend/commit/c704c86ca6388b64595def10ac662739471f8959)
