### ISSUE TITLE
Problem page in mobile version broke

### ISSUE THREAD

**Issue by MasterIceZ** [phakphum-dev/otog-frontend#82]
![image](https://user-images.githubusercontent.com/64594596/236758407-317b19f1-cb92-4ccb-a926-dd4649367b97.png)

**Comment by Thunyatorn** [comment]
issue @เสม็ด

**Comment by Anon-136** [comment]
skill issue @เสม็ด

**Comment by Anon-136** [comment]
fixed in 8775365
