### ISSUE TITLE
otog mobile rendering

### ISSUE THREAD

**Issue by Thunyatorn** [phakphum-dev/otog-frontend#84]
![image](https://github.com/phakphum-dev/otog-frontend/assets/58735442/d9779963-69d2-4eb7-bca4-832abf94e875)

โจทย์วันนี้ตัวใหญ่ เกียน❓หรือไม่

**Comment by Anon-136** [comment]
ไปสเม็ดมาหรอ

**Comment by Thunyatorn** [comment]
99% ของคนไปสเม็ด เปิด issue ในโทรศัพท์ ❓

**Comment by Thunyatorn** [comment]
@Anon-136 ![image](https://github.com/phakphum-dev/otog-frontend/assets/58735442/1435458e-7ec1-449f-b997-29a96602c8b8) ทำไมปุ่มกดเข้าไปหน้าแก้ไขอยู่ข้างโจทย์ ยังไม่ผ่าน

**Comment by Anon-136** [comment]
นั่น น่ะ สิ

**Comment by Anon-136** [comment]
@Thunyatorn how to reproduce วะ

> @Anon-136 ![image](https://user-images.githubusercontent.com/58735442/237134037-1435458e-7ec1-449f-b997-29a96602c8b8.png) ทำไมปุ่มกดเข้าไปหน้าแก้ไขอยู่ข้างโจทย์ ยังไม่ผ่าน
