### ISSUE TITLE
แก้ไข UI ผลตรวจ

### ISSUE THREAD

**Issue by Thunyatorn** [phakphum-dev/otog-frontend#86]
![image](https://github.com/phakphum-dev/otog-frontend/assets/58735442/b51b1335-aa9d-41ae-ab34-b5b2bf0776e0)

**Comment by Anon-136** [comment]
@MasterIceZ @Thunyatorn

**Comment by ttamx** [comment]
gean ❓

**Comment by MasterIceZ** [comment]
แก้เป็นเลขดิวะ

**Comment by Thunyatorn** [comment]
เพิ่มปุ่มแสดงรายละเอียดผลตรวจ

**Comment by Anon-136** [comment]
รายละเอียดอะไรวะ

**Comment by Anon-136** [comment]
#97 done
