### ISSUE TITLE
เพิ่มระบบ rejudge เฉพาะ submission

### ISSUE THREAD

**Issue by Thunyatorn** [phakphum-dev/otog-frontend#91]
![image](https://github.com/phakphum-dev/otog-frontend/assets/58735442/21a18de0-0ded-421f-a8d1-39249a409e4a)

**Comment by Anon-136** [comment]
เอาปุ่มไว้ตรงไหนดี

**Comment by Thunyatorn** [comment]
ข้างๆ ปุ่ม share

**Comment by Anon-136** [comment]
should be done fb10ce4
